### PR TITLE
update function build_dataset_iteratively to reflect taking start symbol and end symbol for range download

### PR DESCRIPTION
**Pull request by GuangMo**

### CODE REVIEW

**Comment by GuangMo** [comment]
sorry Robert, I accidentally "commit -a -m" to include the stock csv, and I only have another hour to play on GitHub today, so I did not revert my change and redo them again, please feel free to only modify the change on your function and abandon the PR. Great work by the way!

**Comment by robertmartin8** [comment]
@GuangMo My apologies for the late response – I will review the modifications and try to merge them some time this coming week

**Comment by robertmartin8** [comment]
@GuangMo I have reviewed it – I understand what you are trying to do, but I think this should be a new function rather than overwriting the current one

**Comment by GuangMo** [comment]
Sounds good, Robert! I will leave it up to you then :)

**Pull request closed without merging**
